baseURL = "http://prideness.fr/"
languageCode = "en-us"
title = "Merwan SETITA"
theme = "paige"
enableEmoji = true
publishDir="public/main"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[languages.en]
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 100

[languages.en.menu.main.params.paige]
disabled = true

# [[languages.en.menu.main]]
# identifier = "life"
# name = "Life"
# parent = "blog"
# url = "/blog/life/"
# weight = 10

# [[languages.en.menu.main]]
# identifier = "work"
# name = "Work"
# parent = "blog"
# url = "/blog/work/"
# weight = 20

# [languages.en.menu.main.params.paige]
# divider_below = true

# [[languages.en.menu.main]]
# identifier = "interests"
# name = "Interests"
# parent = "blog"
# url = "/blog/interests/"
# weight = 30

[[languages.en.menu.main]]
identifier = "resume"
name = "Resume"
url = "/resume/"
weight = 15

[[languages.en.menu.main]]
identifier = "link"
name = "Links"
url = "/links/"
weight = 20

[[languages.en.menu.main]]
identifier = "other"
name = "Other"
url = "/other/"
weight = 20


# [[languages.en.menu.main]]
# identifier = "search"
# name = "Search"
# url = "/search/"
# weight = 40
